[package]
name = "arc104"
version = "0.1.0"
authors = ["Hinagi <hasevent@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
